name: OmniLIB
version: '${project.version}'
main: me.ikevoodoo.omnilib.OmniLIB
api-version: 1.17
load: STARTUP
authors: [ IkeVoodoo ]
description: Library for other plugins to use, no features are provided.
